---
name: Philip Qing An 
surname: Khor
position: Data Scientist
address: Georgetown, Malaysia
phone: +60 16 720 2723
www: philipscurve.com
email: pk.qa@outlook.com
twitter: philip_khor
github: philip-khor
linkedin: philip-khor
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Summary

Data professional with a background in Economics and research experience in applied microeconometrics. Fluent in Python machine learning using scikit-learn and data wrangling with R using tidyverse packages.

# Work Experience and Training 

```{r}
tribble(
  ~ Company, ~ Year, ~ Position, ~ Location, 
  "GRID Inc.", "May 2019 - August 2019", "Data Scientist Intern", "Omote-sando, Tokyo",
  "The Center of Applied Data Science", "July 2018 - May 2019", "Data Scientist Associate", "Bangsar South, Kuala Lumpur",
  "ASEAN Data Analytics eXchange", "Feb 2018 - June 2018", "Data Scientist Trainee", "Bangsar South, Kuala Lumpur", 
  "Penang Institute", "Aug 2016 - Jan 2017", "Research Assistant", "George Town, Penang"
) %>% 
  mutate(Details = list(
    c("Train real-time object detection and image segmentation
       models for use in agriculture using Yolov2, SSD and Mask R-CNN
       deep learning architectures with internally built framework.", 
      "Delivered substantial improvement on performance of
       previously built internal model"), 
    c("Delivered over 100 hours in training sessions for Microsoft 
       Excel, R for Analytics, Tableau, Statistics and Data Storytelling", 
      "Developing training products in the areas of statistics, 
       exploratory analysis, data visualization and machine learning 
       using spreadsheets, R, Python and Tableau delivered through 
       tools such as Jupyter Notebooks and R Markdown, focusing on 
       commercial applications of data science",
      "Module leader for Excel Analytics and Regression Modelling 
       and Evaluation module",
      "Core developer of introductory and intermediate 
       Statistics and R for Analytics modules",
      "Also involved in developing training material for 
       Natural Language Processing, Neural Networks, Data Visualisation 
       with Tableau, A/B/n Testing and Time Series Analytics and Forecasting modules"), 
    c("Data science finishing school for graduates covering R and Python 
       programming modules, machine learning in scikit-learn, visualisation 
       in ggplot2, seaborn, matplotlib and Tableau, forecasting in R and 
       natural language processing in NLTK."), 
    c("Provided research assistance for the Penang Skilled Workforce Study project, which identifies skills shortages and skill gaps in key economic sectors in Penang.",
      "Scheduled and performed interviews with Human Resource, company executives and other governmental and non- governmental stakeholders.", 
      "Liased with state and federal government agencies to obtain secondary data.", 
      "Emcee at the forum Budgeting Priorities in a Challenging Economic Environment (Nov 2016).")
  )) %>% 
  tidyr::unnest() %>% 
  detailed_entries(Company, Year, Position, Location, Details)
```

# Projects 

```{r}
tribble(
  ~ project_type, ~ year, ~ project_title, ~ location, 
  "Honours thesis", "2017", "Family background and child health: the role of socioeconomic status and skills", "University of Wollongong", 
  "", "Aug 2017 - Jan 2017", "Penang Skilled Workforce Study", "Penang Institute"
) %>% 
  mutate(details = list(
    c("Econometric analysis of the relationship between parental income and child health status in Australia using two large longitudinal datasets."), 
    c("Identification of skill gaps and skill shortages in major Penang economic sectors through qualitative interviews and desk research.")
  )) %>% 
  detailed_entries(project_type, year, project_title, location, details)
```

\newpage 

# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, 
  "Bachelor of Commerce (Honours)", "2017", "University of Wollongong", "NSW, Australia",
  "Bachelor of Commerce (Dean's Scholar)", "2014-2016", "University of Wollongong", "NSW, Australia",
  "Diploma in Business Studies", "2012-2014", "Tunku Abdul Rahman University College", "George Town, Penang"
) %>% 
  mutate(Details = list(
  c("Received the 2017 Honours Scholarship from the Faculty of Business 
     based on academic performance, research and leadership potential.", 
    "Undertook a research project as part of coursework for 
     Advanced Macroeconomic Theory (Health and wealth: economic 
     growth with endogenous health and human capital.)"), 
  c("Admitted to the Dean’s Scholar program in 
     recognition of high academic achievement.", 
    "Awarded the Business International Academic
     Merit Scholarship and the Undergraduate Excellence 
     Scholarship in recognition of prior academic achievement.", 
    "Awarded the Illawarra Regional Information Services 
     John Steinke Prize in Economics (April 2017) for achieving 
     the highest mark in 300-level Economics subjects in 2016.", 
    "Awarded the Kenneth A. Blakey Prize (March 2015) for 
     achieving the highest aggregate mark in Microeconomic Theory
     and Policy in 2014.", 
    "Consistently placed in the Dean’s Merit List (2014-2017), 
     which ranks the top 5% of students in the Faculty of Business."), 
  c("Received the Merit Scholarship amounting to 100% of the tuition fees 
     for the length of the program in recognition of prior academic performance", 
    "Awarded Book Prize"))) %>% 
  tidyr::unnest() %>% 
  detailed_entries(Degree, Year, Institution, Where, Details)
```




