# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 'cv/**'
  pull_request:
    branches: [ main ]
    paths: 'cv/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_PAK_ENABLED: false
      RENV_CONFIG_PPM_ENABLED: true
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
            
      - uses: r-lib/actions/setup-pandoc@v2
        
      - uses: r-lib/actions/setup-renv@v2
      
      - uses: r-lib/actions/setup-tinytex@v2
      
      - name: Render Rmarkdown files
        run: rmarkdown::render("cv/philip_khor-cv.Rmd")
        shell: Rscript {0}
        
      - uses: actions/upload-artifact@v3
        with:
          name: cv
          path: "*.pdf"
